"""Write docs/ENVIRONMENT.md: OS, Python, pip freeze, conda (if any), torch / CUDA / cuDNN, GPU and driver, and every model
weight file used (name, source, revision, SHA256). Run on the machine that produced the results.

  python scripts/verify/environment_report.py
"""
from __future__ import annotations

import hashlib
import os
import platform
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HF_ROOTS = [Path("/workspace/.hf_home/hub"), Path("/root/data/cache/hf")]
WEIGHTS = [  # (name in the code, source, local file or HF repo)
    ("dino518 / dino224 (DINOv2 ViT-B/14)", "torch.hub facebookresearch/dinov2", "/root/.cache/torch/hub/checkpoints/dinov2_vitb14_pretrain.pth"),
    ("dinos518 (DINOv2 ViT-S/14)", "torch.hub facebookresearch/dinov2", "/root/data/cache/torch_hub/checkpoints/dinov2_vits14_pretrain.pth"),
    ("dinol518 (DINOv2 ViT-L/14)", "torch.hub facebookresearch/dinov2", "/root/data/cache/torch_hub/checkpoints/dinov2_vitl14_pretrain.pth"),
    ("raddino518 (RAD-DINO)", "Hugging Face", "microsoft/rad-dino"),
    ("medsiglip448 (MedSigLIP)", "Hugging Face (gated: accept terms)", "google/medsiglip-448"),
    ("dermlip224 (DermLIP PanDerm-base)", "Hugging Face", "redlessone/DermLIP_PanDerm-base-w-PubMed-256"),
    ("convnext384 (ConvNeXt-B)", "Hugging Face / timm", "timm/convnext_base.fb_in22k_ft_in1k_384"),
    ("fine-tuning: ConvNeXt-T", "Hugging Face / timm", "timm/convnext_tiny.fb_in22k_ft_in1k"),
    ("fine-tuning: ResNet-50", "Hugging Face / timm", "timm/resnet50.a1_in1k"),
    ("fine-tuning: ViT-S/16", "Hugging Face / timm", "timm/vit_small_patch16_224.augreg_in21k_ft_in1k"),
    ("fine-tuning recipe grid: DINOv2 ViT-B (timm)", "Hugging Face / timm", "timm/vit_base_patch14_dinov2.lvd142m"),
    ("lesion U-Net encoder (segmentation_models_pytorch)", "Hugging Face", "smp-hub/resnet34.imagenet"),
    ("MedGemma (round 6 label source)", "Hugging Face (gated: accept terms)", "google/medgemma-1.5-4b-it"),
    ("text embeddings (round 6)", "Hugging Face", "neuml/pubmedbert-base-embeddings"),
    ("LaMa big-lama (simple-lama-inpainting 0.1.2)", "github.com/enesmsahin/simple-lama-inpainting release v0.1.0", "/root/.cache/torch/hub/checkpoints/big-lama.pt"),
    ("lung segmentation (torchxrayvision chestx_det PSPNet)", "torchxrayvision release", "/root/.torchxrayvision/models_data/pspnet_chestxray_best_model_4.pth"),
]


def sh(cmd: str) -> str:
    try:
        return subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.STDOUT).strip()
    except subprocess.CalledProcessError as e:
        return (e.output or "").strip() or f"(failed: {cmd})"


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 22), b""):
            h.update(b)
    return h.hexdigest()


def hf_files(repo: str):
    """(revision, [(relative file, size, sha256)]) of the weight files of a cached HF repo."""
    for root in HF_ROOTS:
        d = root / ("models--" + repo.replace("/", "--"))
        if not d.exists():
            continue
        ref = (d / "refs" / "main").read_text().strip() if (d / "refs" / "main").exists() else ""
        snaps = sorted((d / "snapshots").iterdir()) if (d / "snapshots").exists() else []
        snap = d / "snapshots" / ref if ref and (d / "snapshots" / ref).exists() else (snaps[-1] if snaps else None)
        if snap is None:
            continue
        files = [p for p in sorted(snap.rglob("*")) if p.is_file() and p.suffix in (".safetensors", ".bin", ".pth", ".pt")]
        return snap.name, [(str(p.relative_to(snap)), p.stat().st_size, sha256(p.resolve())) for p in files]
    return None, []


def main():
    import torch
    L = ["# Environment (machine that produced the results)", "",
         "Generated by `scripts/verify/environment_report.py` on 2026-09-29.", "", "## System", ""]
    osr = sh("grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '\"'")
    L += [f"- OS: {osr}; kernel {platform.release()}; unprivileged Docker container (Vast.ai base image)",
          f"- Python: {platform.python_version()} (`/venv/main`)",
          f"- torch {torch.__version__}; CUDA (torch build) {torch.version.cuda}; cuDNN {torch.backends.cudnn.version()}",
          f"- GPU: {sh('nvidia-smi --query-gpu=name,memory.total --format=csv,noheader')}; driver "
          f"{sh('nvidia-smi --query-gpu=driver_version --format=csv,noheader')}",
          f"- CPU cores visible: {sh('nproc')}; container CPU quota: {sh('cat /sys/fs/cgroup/cpu.max')} (quota/period); "
          f"RAM: {round(os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES') / 2**30)} GB", "",
          "## Model weights", "", "| used as | source | revision / file | size | SHA256 |", "|---|---|---|---|---|"]
    for name, src, loc in WEIGHTS:
        if loc.startswith("/"):
            p = Path(loc)
            if p.exists():
                L.append(f"| {name} | {src} | `{p.name}` | {p.stat().st_size} | `{sha256(p)}` |")
            else:
                L.append(f"| {name} | {src} | `{p.name}` (not on disk) | | |")
        else:
            rev, files = hf_files(loc)
            if not files:
                L.append(f"| {name} | {src} `{loc}` | not in the local cache | | |")
            for f, size, h in files:
                L.append(f"| {name} | {src} `{loc}` | revision `{rev}`: `{f}` | {size} | `{h}` |")
    conda = sh("command -v conda >/dev/null && conda list --explicit 2>/dev/null | head -400 || echo 'conda not used for the project environment'")
    L += ["", "## conda", "", "```", conda, "```", "", "## pip freeze (`/venv/main`)", "", "```",
          sh("/venv/main/bin/python -m pip freeze 2>/dev/null || uv pip freeze --python /venv/main/bin/python"), "```", ""]
    (ROOT / "docs" / "ENVIRONMENT.md").write_text("\n".join(L) + "\n")
    print("written docs/ENVIRONMENT.md")


if __name__ == "__main__":
    main()
