"""Supplement S16 tables: copies of the generated Stage 7-8 tables (rounds 4-7) with journal wording.

The stage reports refer to "Stage 3", "R10", "A2" and so on; the paper does not. This script copies each generated
table, expands the stage macros to their values, replaces those internal names and prefixes the labels, so the numbers
stay exactly those of the stage generators.
  python scripts/make_paper_round_tables.py      -> paper/tables/s16_*.tex
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
S7 = ROOT / "stages" / "stage7_robustness_external" / "tables"
S8 = ROOT / "stages" / "stage8_labels_strong_model" / "tables"
OUT = ROOT / "paper" / "tables"
TABLES = [(S7, "r8_crossover"), (S7, "r8_contrast"), (S7, "r9_slopes"), (S7, "r12_tiers"), (S7, "r13_groups"), (S7, "r11"),
          (S8, "coverage"), (S8, "isic_agree"), (S8, "thyroid_labellers"), (S8, "thyroid_consensus"), (S8, "cleaned"),
          (S8, "recipe"), (S8, "ft"), (S8, "op_ft"), (S8, "matched"), (S8, "matched_other")]
WORDS = [("Stage~3 protocol", "protocol of the real traps"), ("Stage 3 crossover", "Original crossover"),
         ("reproduces Stage~3", "reproduces the original analysis"),
         ("the other natural test sets of Stage~5", "the other unaltered test sets"),
         ("(A2; ", "("), ("& HA2 \\\\", "& Registered test \\\\"), ("Recipe selection on validation images only (B1)",
                                                                      "Recipe selection on validation images only"),
         ("after the exclusions of Amendment~1", "after the registered exclusions"),
         ("calibrated (R12 primary)", "calibrated (primary)"), ("(R10)", "(registered)"), (" (R13)", ""),
         ("committed before any model of round 5 was fitted", "committed before any model of this analysis was fitted"),
         ("T1$'$ reversed AUROC, all new cells", "Reversed AUROC, all new cells"),
         ("T2$'$ R8 crossovers", "Masking-implementation crossovers"), ("T3$'$ R9 slopes", "Overlap dose-response slopes"),
         ("T3$'$ R9 bin gains", "Overlap-bin gains"), ("Round 7, descriptive: ", "Descriptive: "),
         ("Round 7: sensitivity", "Sensitivity"), ("\\ok", "supported"), ("\\mixed", "partly supported"),
         ("\\no{}", "not supported")]


def macros() -> dict:
    out = {}
    for f in (S7 / "numbers.tex", S8 / "numbers.tex"):
        for m in re.finditer(r"\\providecommand\{\\(\w+)\}\{(.*)\}$", f.read_text(), re.M):
            out[m.group(1)] = m.group(2)
    return out


def main():
    mac = macros()
    OUT.mkdir(parents=True, exist_ok=True)
    for d, name in TABLES:
        t = (d / f"{name}.tex").read_text()
        t = re.sub(r"\\(s(?:Seven|Eight)\w+)(\{\})?", lambda m: mac[m.group(1)], t)
        for a, b in WORDS:
            t = t.replace(a, b)
        t = re.sub(r"\\label\{tab:", r"\\label{tab:s16", t)
        left = re.findall(r"Stage[~ ]\d|\bR1?\d\b|\bHA2\b|Amendment|[Rr]ound \d", t)
        if left:
            raise SystemExit(f"{name}: internal names left: {sorted(set(left))}")
        (OUT / f"s16_{name}.tex").write_text(f"% generated by scripts/make_paper_round_tables.py from {d.name}/{name}.tex\n" + t)
    print("S16 tables written:", len(TABLES))


if __name__ == "__main__":
    main()
