"""Main paper table: in-ROI (Trap A) reversed AUROC and min(reversed, correlated) for every cohort × backbone.

  python scripts/make_main_table.py     # -> paper/tables/main_inroi.tex
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

from wtss import paths

spec = importlib.util.spec_from_file_location("cc", Path(__file__).with_name("make_cross_cohort_table.py"))
cc = importlib.util.module_from_spec(spec); spec.loader.exec_module(cc)

ROWS = [("erm", "ERM", "—"), ("mask", "ROI masking", "ROI"), ("U-mte_aug", "Mask + overlay augmentation", "ROI"),
        ("U-mte", "\\textbf{U-MtE (ours)}", "ROI"), ("U-mte_protect", "\\textbf{U-MtE, protected (ours)}", "ROI + $Y$ of $A{=}0$"),
        ("balanced", "Group-balanced", "$A$"), ("dfr", "DFR", "$A$"), ("U-mask_dfr", "Mask + DFR", "ROI + $A$"),
        ("U-mte_balanced", "\\textbf{U-MtE + balanced (ours)}", "ROI + $A$")]
COLS = [("ISIC 2019 hair", "DINOv2"), ("ISIC 2019 hair", "DermLIP"), ("Thyroid US markers", "DINOv2"),
        ("Thyroid US markers", "MedSigLIP"), ("Thyroid US markers", "ConvNeXt"), ("Capsule debris", "DINOv2"),
        ("Capsule debris", "MedSigLIP"), ("Capsule debris", "ConvNeXt"), ("NIH chest drains (in-ROI only)", "RAD-DINO"),
        ("NIH chest drains (in-ROI only)", "DINOv2")]
SHORT = {"ISIC 2019 hair": "Hair", "Thyroid US markers": "Thyroid", "Capsule debris": "Capsule",
         "NIH chest drains (in-ROI only)": "Drain"}


def main():
    data = {c: cc.load(c) for c in COLS}
    cols = [c for c in COLS if data[c]]
    head = " & ".join(f"\\rotatebox{{90}}{{{SHORT[c[0]]}/{c[1]}}}" for c in cols)
    lines = ["\\begin{table*}[t]\\centering\\scriptsize",
             "\\caption{In-ROI artifacts (Trap~A): reversed-test AUROC, with min(reversed, correlated) in parentheses "
             "(penalises shortcut flipping). Best robust value per column in bold. Generated by \\texttt{scripts/make\\_main\\_table.py}.}",
             "\\label{tab:main}", "\\resizebox{\\textwidth}{!}{\\begin{tabular}{ll" + "c" * len(cols) + "}", "\\toprule",
             f"Method & Needs & {head} \\\\", "\\midrule"]
    best = {}
    for c in cols:
        vals = [min(data[c][("trapA", k, "test_rev")], data[c][("trapA", k, "test_corr")])
                for k, _, _ in ROWS if ("trapA", k, "test_rev") in data[c]]
        best[c] = max(vals) if vals else None
    for key, name, needs in ROWS:
        cells = []
        for c in cols:
            r, k = data[c].get(("trapA", key, "test_rev")), data[c].get(("trapA", key, "test_corr"))
            if r is None:
                cells.append("–")
                continue
            m = min(r, k)
            s = f"{r:.2f} ({m:.2f})"
            cells.append(f"\\textbf{{{s}}}" if best[c] is not None and abs(m - best[c]) < 1e-9 else s)
        lines.append(f"{name} & {needs} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table*}"]
    out = paths.REPO_ROOT / "paper" / "tables" / "main_inroi.tex"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
