"""Assemble the seven stage reports into one document (stages/combined/full_report.tex).

Each stage becomes one top-level section; its sections become subsections. The body of every stage and the generated
tables it includes are copied verbatim (labels prefixed per stage so they do not collide, file paths rewritten), so the
combined report shows exactly the numbers of the stage reports. Run make_stageN.py first (or bash stages/build_all.sh).
  python stages/combined/make_combined.py"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
STAGES = HERE.parent
DIRS = sorted(p for p in STAGES.glob("stage[1-7]_*") if p.is_dir())
TITLES = {1: "The problem, the pilot and the protocol", 2: "The location law and its mechanism",
          3: "Real artifacts across modalities", 4: "Is it location, or which images carry the artifact?",
          5: "Practice, breadth and theory", 6: "What to do instead of masking, and the state of the thesis",
          7: "How robust is the location law?"}


def demote(s: str) -> str:
    s = re.sub(r"\\subsubsection(\*?)\{", r"\\paragraph\1{", s)
    s = re.sub(r"\\subsection(\*?)\{", r"\\subsubsection\1{", s)
    return re.sub(r"\\section(\*?)\{", r"\\subsection\1{", s)


def relabel(s: str, n: int) -> str:
    return re.sub(r"\\(label|ref|pageref)\{([^}]+)\}", lambda m: f"\\{m.group(1)}{{s{n}:{m.group(2)}}}", s)


def inline_tables(s: str, d: Path) -> str:
    def rep(m):
        f = d / "tables" / (m.group(1) if m.group(1).endswith(".tex") else m.group(1) + ".tex")
        return f.read_text() if f.exists() else m.group(0)
    return re.sub(r"\\input\{tables/([^}]+)\}", rep, s)


def body(n: int, d: Path) -> str:
    t = (d / f"stage{n}.tex").read_text()
    t = t[t.index("\\maketitle") + len("\\maketitle"):t.index("\\bibliographystyle")]
    t = re.sub(r"\\input\{\.\./common/notation\.tex\}\s*", "", t)
    t = re.sub(r"\\tableofcontents\s*\\clearpage\s*", "", t)
    t = t.replace("\\input{tables/numbers.tex}", "")
    t = inline_tables(t, d)
    t = t.replace("This report", "This stage").replace("this report", "this stage")
    t = t.replace("\\section{Purpose of this stage}", "\\section{Purpose of this stage}")
    t = relabel(t, n)
    t = demote(t)
    rel = f"../{d.name}/"
    t = t.replace("{figures/", "{" + rel + "figures/")
    return f"\\section{{Stage {n} --- {TITLES[n]}}}\\label{{sec:stage{n}}}\n" + t


def main():
    nums = "\n".join(f"\\input{{../{d.name}/tables/numbers.tex}}" for d in DIRS)
    (HERE / "numbers_all.tex").write_text("% generated by make_combined.py\n" + nums + "\n")
    for k, d in enumerate(DIRS, start=1):
        (HERE / f"body_stage{k}.tex").write_text("% generated by make_combined.py from " + d.name + f"/stage{k}.tex; do not edit\n" + body(k, d))
    print("combined bodies written:", len(DIRS))


if __name__ == "__main__":
    main()
